# docker-compose.yml
redis:
  image: redis
  container_name: cache
  expose:
    - 6379

worker:
  build: ./
  volumes:
    - ./:/var/www/app
  links:
    - redis
  environment:
    - NODE_ENV=development
    - REDIS_URL=redis://cache
  command: sh -c 'npm i && npm run worker'

app:
  build: ./
  volumes:
    - ./:/var/www/app
  links:
    - redis
    - worker
  ports:
    - 3000:3000
  environment:
    - NODE_ENV=development
    - PORT=3000
    - REDIS_URL=redis://cache
  command: sh -c 'npm i && npm run server'
